# Generated by Django 3.2.19 on 2023-06-07 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Academy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academy_id', models.IntegerField()),
                ('academy_name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'app_academy',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('sex', models.CharField(max_length=1)),
                ('tel', models.CharField(max_length=11)),
                ('birth', models.DateField()),
                ('address', models.CharField(max_length=50)),
                ('academy_id', models.IntegerField()),
                ('specialize_id', models.IntegerField()),
            ],
            options={
                'db_table': 'app_contact',
            },
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission', models.CharField(max_length=10)),
                ('handle', models.TextField()),
            ],
            options={
                'db_table': 'app_permission',
            },
        ),
        migrations.CreateModel(
            name='Specialize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialize_id', models.IntegerField()),
                ('specialize_name', models.IntegerField()),
            ],
            options={
                'db_table': 'app_specialize',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('sid', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('sex', models.CharField(max_length=1)),
                ('tel', models.CharField(max_length=11)),
                ('permission', models.CharField(max_length=10)),
                ('identity', models.IntegerField()),
            ],
            options={
                'db_table': 'app_user',
            },
        ),
    ]
