# Generated by Django 3.2.19 on 2023-06-07 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_user_sex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='id',
            field=models.BigIntegerField(auto_created=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='sid',
            field=models.BigIntegerField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
