# Generated by Django 3.2.19 on 2023-06-08 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20230607_2243'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Academy',
        ),
        migrations.AddField(
            model_name='specialize',
            name='academy_name',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='specialize',
            name='specialize_name',
            field=models.CharField(max_length=50),
        ),
    ]
