# Generated by Django 3.2.19 on 2023-06-08 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20230608_1225'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Permission',
        ),
        migrations.RemoveField(
            model_name='user',
            name='permission',
        ),
    ]
